### ISSUE TITLE
Why iterate mod in self.module_list?

### ISSUE THREAD

**Issue by BlueMatrix007** [FerranAlet/modular-metalearning#4]
https://github.com/FerranAlet/modular-metalearning/blob/fb7dbf07abe3799878cdabc63b8150628b35dc5d/functioncomposition_composer.py#L21

**Comment by BlueMatrix007** [comment]
Should we iterate mod in self.structure['modules'], like the code in forward_with_weights()

**Comment by FerranAlet** [comment]
Fixed, thanks @BlueMatrix007! It doesn't change the results of the paper because we were only using it for MAML with module_list of 1 module, but it was certainly a bug. 
Sorry for the late response, I saw your issue only a couple days ago and wanted to make sure I understood if the bug had further consequences.
